services:
  db:
    image: postgres:16-alpine
    restart: on-failure
    environment:
      - POSTGRES_DB=wfdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local